#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
1. Add a book
2. Edit book info
3. View book list
4. Exit
EOS

choose do |menu|
  menu.prompt = ""

  books_controller = BooksController.new
  menu.choice('Add a book')  { say("What is the book's title?\n") }
  menu.choice('Edit book info') { say("No books found. Add a book.\n") }
  menu.choice('View book list') { books_controller.index }
  menu.choice('Exit') { say("Go read something!\n") }

end
